site_name: Documentation Open Science Knowledge Graph
site_description: This project builds a reproducible and FAIR pipeline to analyze 30 open-access research papers and turn the results into an RDF Knowledge Graph that can be queried with SPARQL. We thought this project on a bigger scale could be a useful resource for the scientific community, and we hope it can inspire others to do similar work.

theme:
  name: material
  language: es
  features:
    - navigation.tabs
    - navigation.sections
    - search.highlight
    - content.code.copy

nav:
  - Inicio: index.md
  - AI Use Declaration: ai_use_declaration.md
  - Experiment Design: experiment_design.md
  - External Sources: external_sources.md
  - Limitations: limitations.md
  - Model Decisions: model_decisions.md
  - Ontology Diagram: ontology_diagram.md
  - Ontology: ontology.md
  - Provenance: provenance.md
  - Use Case: use_case.md
  - Workflow: workflow.md

plugins:
  - search

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - pymdownx.highlight
  - pymdownx.superfences