# Papers and the persons/organizations they acknowledge.
PREFIX oskg: <http://example.org/oskg/ontology#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?paper ?entity ?entityName ?entityType
WHERE {
  ?paper a oskg:Paper ;
         oskg:acknowledges ?entity .
  ?entity foaf:name ?entityName ;
          rdf:type ?entityType .
  FILTER (?entityType IN (oskg:Person, oskg:Organization))
}
ORDER BY ?paper ?entityType
